@baseUrl=http://localhost:3000
@basePath=auth

POST {{baseUrl}}/{{basePath}}/signup HTTP/1.1
content-type: application/json

{
    "username":"dlohani",
    "password":"##d3dsf219Adx"
}
###

POST {{baseUrl}}/{{basePath}}/signin HTTP/1.1
content-type: application/json

{
    "username":"dlohani",
    "password":"##d3dsf219Adx"
}

###
POST {{baseUrl}}/{{basePath}}/test HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRsb2hhbmkiLCJpYXQiOjE2MDE5OTY4MjIsImV4cCI6MTYwMjAwMDQyMn0.-1q17-t7CyhYKZH8vyP4sj5GVrSCK736qjwj0fFSWec