@baseUrl=http://localhost:3000
@basePath=auth

POST {{baseUrl}}/{{basePath}}/signup HTTP/1.1
content-type: application/json

{
    "username":"dlohani",
    "password":"##d3dsf219Adx"
}
###

POST {{baseUrl}}/{{basePath}}/signin HTTP/1.1
content-type: application/json

{
    "username":"dlohani",
    "password":"##d3dsf219Adx"
}

###
POST {{baseUrl}}/{{basePath}}/test HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRsb2hhbmkiLCJpYXQiOjE2MDE5OTU3MzEsImV4cCI6MTYwMTk5OTMzMX0.HJH3gG2mBg3HIE7pvJOtshj4wcu47YG97Y7vKHMnFBQ