@baseUrl=http://localhost:3000
@basePath=tasks
@taskId=2

GET {{baseUrl}}/{{basePath}} HTTP/1.1

###
GET {{baseUrl}}/{{basePath}}?status=DONE&search=SHI HTTP/1.1

###
//invalid filter request
GET {{baseUrl}}/{{basePath}}?status=ded&search= HTTP/1.1

###

POST {{baseUrl}}/{{basePath}} HTTP/1.1
Content-Type: application/json

{
    "title":"Share market",
    "description":"I should remember to check SHIVAM shares"
}
###
//invalid request
POST {{baseUrl}}/{{basePath}} HTTP/1.1
Content-Type: application/json

{
    "title":"",
    "description":"I should remember to check SHIVAM shares"
}
###

PATCH  {{baseUrl}}/{{basePath}}/{{taskId}}/status HTTP/1.1
Content-Type: application/json

{
    "status":"DONE"
}

###
//invalid status request
PATCH  {{baseUrl}}/{{basePath}}/{{taskId}}/status HTTP/1.1
Content-Type: application/json

{
    "status":"in_progres"
}

###

GET {{baseUrl}}/{{basePath}}/{{taskId}} HTTP/1.1

###

DELETE {{baseUrl}}/{{basePath}}/{{taskId}} HTTP/1.1