@baseUrl=http://localhost:3000
@basePath=tasks
@taskId=8ceedefc-7194-4994-9fe1-88507f3cf4bc

GET {{baseUrl}}/{{basePath}} HTTP/1.1

###
GET {{baseUrl}}/{{basePath}}?status=DONE&search=share HTTP/1.1

###

POST {{baseUrl}}/{{basePath}} HTTP/1.1
Content-Type: application/json

{
    "title":"Nest Js",
    "description":"I should remember to check SHIVAM shares"
}
###
//invalid request
POST {{baseUrl}}/{{basePath}} HTTP/1.1
Content-Type: application/json

{
    "title":"",
    "description":"I should remember to check SHIVAM shares"
}
###

PATCH  {{baseUrl}}/{{basePath}}/{{taskId}}/status HTTP/1.1
Content-Type: application/json

{
    "status":"DONE"
}

###

GET {{baseUrl}}/{{basePath}}/{{taskId}} HTTP/1.1

###

DELETE {{baseUrl}}/{{basePath}}/{{taskId}} HTTP/1.1