@baseUrl=http://localhost:3000
@basePath=tasks
@taskId=0f5928d3-5c00-4ab2-a9d5-f4e1fa903945

GET {{baseUrl}}/{{basePath}} HTTP/1.1

###

POST {{baseUrl}}/{{basePath}} HTTP/1.1
Content-Type: application/json

{
    "title":"remember to check shares",
    "description":"I should remember to check SHIVAM shares"
}

###

GET {{baseUrl}}/{{basePath}}/{{taskId}} HTTP/1.1

###

DELETE {{baseUrl}}/{{basePath}}/{{taskId}} HTTP/1.1